services:
  service:
    build: ./service
    ports:
      - "3002:5000"
    depends_on:
      influx:
        condition: service_started
  database:
    image: mongo
    restart: always
    environment:
      # keep in mind, instance is only accessible in vpc
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
