services:
  service:
    build: ./service
    ports:
      - "3005:3005"
    depends_on:
      database:
        condition: service_started
  database:
    image: mongo:8.0.3-noble
    restart: always
    environment:
      # keep in mind, instance is only accessible in vpc
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
