FROM grafana/grafana-oss:11.3.1

COPY config.ini /etc/grafana/grafana.ini
COPY dashboard.json /etc/grafana/dashboards/
COPY datasources.yaml /etc/grafana/provisioning/datasources/
COPY dashboards.yaml /etc/grafana/provisioning/dashboards/
